# Run with:
# docker compose -f robot/compose_real.yml up
services:
  aloha_act:
    image: aloha_act
    depends_on:
      - aloha_ros_nodes
      - ros_master
    build:
      context: ..
      dockerfile: robot/Dockerfile
    init: true
    tty: true
    network_mode: host
    privileged: true
    volumes:
      - ./data:/data
      - ./ckpts:/ckpts
    command:
      - python
      - imitate_episodes.py
      - --task_name
      - aloha_wear_shoe
      - --ckpt_dir
      - /ckpts
      - --eval
      - --policy_class
      - PI
      - --kl_weight
      - "10"
      - --chunk_size
      - "100"
      - --hidden_dim
      - "512"
      - --batch_size
      - "8"
      - --dim_feedforward
      - "3200"
      - --num_epochs
      - "2000"
      - --lr
      - "1e-5"
      - --seed
      - "0"
      - --render_height
      - "256"
      - --render_width
      - "320"

  aloha_ros_nodes:
    image: aloha_act
    depends_on:
      - ros_master
    build:
      context: ..
      dockerfile: robot/Dockerfile
    init: true
    tty: true
    network_mode: host
    privileged: true
    volumes:
      - /dev:/dev
    command:
      - roslaunch
      - --wait
      - aloha
      - ros_nodes.launch

  ros_master:
    image: ros:noetic-robot
    network_mode: host
    privileged: true
    command:
      - roscore