services:
  trossen_device:
    image: trossen_device
    depends_on:
      - ros_master
    build:
      context: ..
      dockerfile: robot/Dockerfile
    tty: true
    network_mode: host
    environment:
      - ARM_ROLE=puppet

  ros_master:
    image: ros:noetic-robot
    network_mode: host
    privileged: true
    command:
      - roscore