# Run with:
# docker compose -f robot/compose_real.yml up
services:
  aloha_act:
    image: aloha_act
    depends_on:
      - ros_master
    build:
      context: ..
      dockerfile: robot/Dockerfile
    init: true
    tty: true
    network_mode: host
    privileged: true
    volumes:
      - /dev:/dev
    environment:
      - ARM_ROLE=puppet

  ros_master:
    image: ros:noetic-robot
    network_mode: host
    privileged: true
    command:
      - roscore