port: /dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_$ARM_SERIAL_ID-if00-port0

groups:
  arm:
    operating_mode: position
    profile_type: velocity
    profile_velocity: 0
    profile_acceleration: 0
    torque_enable: true

singles:
  gripper:
    operating_mode: position
    profile_type: velocity
    profile_velocity: 0
    profile_acceleration: 0
    torque_enable: true